### ISSUE TITLE
Invalid search query freezes javascript UI

### ISSUE THREAD

**Issue by weltling** [FriendsOfPHP/pickleweb#43]
When typing the query `hello/` into the search box, the server delivers 500 and the UI doesn't respond anymore. Same with typing a `\` in there. So there are two issues:
- UI freezes when server delivered 500, most likely because the server delivers not a valid json but a usual exception output
- Some chars in the search query, at least known now - `\` and `/`, need some special handling

Here's the exception delivered:

Slim Application Error

The application could not run because of the following error:
Details
Type: Elastica\Exception\ResponseException
Message: SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[dSbwdMkNQSmemFLsqt0NYg][packages][0]: SearchParseException[[packages][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"\"}}}]]]; nested: QueryParsingException[[packages] Failed to parse query []]; nested: ParseException[Cannot parse '\': Lexical error at line 1, column 2. Encountered: after : ""]; nested: TokenMgrError[Lexical error at line 1, column 2. Encountered: after : ""]; }{[dSbwdMkNQSmemFLsqt0NYg][packages][1]: SearchParseException[[packages][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"\"}}}]]]; nested: QueryParsingException[[packages] Failed to parse query []]; nested: ParseException[Cannot parse '\': Lexical error at line 1, column 2. Encountered: after : ""]; nested: TokenMgrError[Lexical error at line 1, column 2. Encountered: after : ""]; }{[dSbwdMkNQSmemFLsqt0NYg][packages][2]: SearchParseException[[packages][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"\"}}}]]]; nested: QueryParsingException[[packages] Failed to parse query []]; nested: ParseException[Cannot parse '\': Lexical error at line 1, column 2. Encountered: after : ""]; nested: TokenMgrError[Lexical error at line 1, column 2. Encountered: after : ""]; }{[dSbwdMkNQSmemFLsqt0NYg][packages][3]: SearchParseException[[packages][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"\"}}}]]]; nested: QueryParsingException[[packages] Failed to parse query []]; nested: ParseException[Cannot parse '\': Lexical error at line 1, column 2. Encountered: after : ""]; nested: TokenMgrError[Lexical error at line 1, column 2. Encountered: after : ""]; }{[dSbwdMkNQSmemFLsqt0NYg][packages][4]: SearchParseException[[packages][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"\"}}}]]]; nested: QueryParsingException[[packages] Failed to parse query []]; nested: ParseException[Cannot parse '\': Lexical error at line 1, column 2. Encountered: after : ""]; nested: TokenMgrError[Lexical error at line 1, column 2. Encountered: after : ""]; }]
File: /app/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php
Line: 158
Trace
#0 /app/vendor/ruflin/elastica/lib/Elastica/Request.php(168): Elastica\Transport\Http->exec(Object(Elastica\Request), Array)
#1 /app/vendor/ruflin/elastica/lib/Elastica/Client.php(603): Elastica\Request->send()
#2 /app/vendor/ruflin/elastica/lib/Elastica/Search.php(443): Elastica\Client->request('/_search', 'GET', Array, Array)
#3 /app/src/Controller/SearchController.php(58): Elastica\Search->search('\')
#4 [internal function]: PickleWeb\Controller\SearchController->searchHtml()
#5 /app/vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array)
#6 [internal function]: RKA\Slim->RKA{closure}()
#7 /app/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#8 /app/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#9 /app/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /app/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /app/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#12 /app/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#13 /app/src/Application.php(181): Slim\Slim->run()
#14 /app/web/index.php(209): PickleWeb\Application->run()
#15 {main}

**Comment by weltling** [comment]
I've found this issue https://github.com/elastic/elasticsearch/issues/2980 which might be useful to know.
